### ISSUE TITLE
specify pass or failure based on returncode and regex

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildntest/schemas#22]
@vsoch 
At the moment buildtest has no mechanism for tweaking pass/failure other than 0 or non-zero for exit code. buildtest can't support expected failure test.

For example at stampede2 we have this test that is expected to fail since ``-n`` is required during job submission.

``` 
version: 0.0.1
missing_total_tasks:
  description: This job fails because '-n' option is required
  type: script
  run: srun -p normal -N1 -t 00:10 hostname
```

Here are few ways we can address this. 

Match by return code
``` 
version: 0.0.1
missing_total_tasks:
  description: This job fails because '-n' option is required
  type: script
  run: srun -p normal -N1 -t 00:10 hostname
  status:
    returncode: 1
```

This test is expected to pass if return code is 1. This would be checked after execution and we would need to process return code match after job execution.  

```
login4.stampede2(996)$ srun -p normal -N1 -t 00:10 hostname

-----------------------------------------------------------------
          Welcome to the Stampede2 Supercomputer
-----------------------------------------------------------------

--> Submission error: please define total core count with the "-n" option
login4.stampede2(997)$ echo $?
1
```

In addition, we can have a regular expression that can be used to read output of stdout or stderr stream. In this case stdout and stderr will refer to the ``.out`` and ``.err`` file where output and error is written. 

For example if want to search for start of string ``--> Submission error`` on stderr stream using ``re.search``. I think we have to limit on the module we can let user's use such as ``re.search``, ``re.match`` so they dont have unexpected results. 

``` 
version: 0.0.1
missing_total_tasks:
  description: This job fails because '-n' option is required
  type: script
  run: srun -p normal -N1 -t 00:10 hostname
  status:
    regex:
      stream: stderr
      exp: "^--> Submission error"
      module: re.search
```

In these two examples, i guess the schema should also one of the two keys ``returncode`` or ``regex``. We shouldn't let user do a returncode match and regex at same time to determine if test is passed.

Let me know your thoughts on this?

**Comment by vsoch** [comment]
This is spot on! I don't think we need to specify "module" under regex - it should be implied that it's re.search, and then it could pose a lot of bugs or security issues if some custom function is provided that needs to be imported. So let' add a status -> returncode that defaults to:

```
version: 0.0.1
missing_total_tasks:
  description: This job fails because '-n' option is required
  type: script
  run: srun -p normal -N1 -t 00:10 hostname
  status:
    returncode: 0
```
If unset, and of course the user can deviate from that for some special status to indicate success. The one potential misleading thing that might happen is if the which statement doesn't find the executable, the error code would be 1, and that wouldn't be the error code for the script but for that call (but the test would pass).

And for regex, I'd tweak to just be:

```bash
version: 0.0.1
missing_total_tasks:
  description: This job fails because '-n' option is required
  type: script
  run: srun -p normal -N1 -t 00:10 hostname
  status:
    regex:
      stream: stderr
      exp: "^--> Submission error"
```
